(()=>{
const $=s=>document.querySelector(s),classes=[
{id:'melee',name:'Vanguard',role:'FRONTLINE • MELEE',icon:'⚔',color:'#e8a55a',desc:'Close the gap. Hit hard and keep moving.',passive:'Battle Rhythm — each kill grants 5% attack speed, up to 20%, for 5 seconds.',hp:130,speed:155,damage:27,rate:.62,weapon:'IRON LONGSWORD',ability:'Whirlwind — spin through nearby enemies.'},
{id:'ranger',name:'Ranger',role:'PRECISION • RANGED',icon:'➶',color:'#9bc79a',desc:'Keep your distance. Make every shot count.',passive:'Deadeye — every fourth basic arrow deals triple damage.',hp:90,speed:180,damage:19,rate:.82,weapon:'HEARTHWOOD BOW',ability:'Volley — loose a storm of arrows.'},
{id:'healer',name:'Keeper',role:'SUPPORT • HEALER',icon:'✣',color:'#80bccc',desc:'Mend your party and punish what gets close.',passive:'Soothing Aura — you and nearby allies restore 2 health per second.',hp:100,speed:160,damage:15,rate:.95,weapon:'MENDER’S CENSER',ability:'Renewal — heal nearby allies.'},
{id:'tank',name:'Bulwark',role:'DEFENSE • TANK',icon:'⬡',color:'#a99ad7',desc:'Stand firm. Draw danger away from your allies.',passive:'Guardian Aura — you and nearby allies take 15% less damage.',hp:180,speed:125,damage:20,rate:.8,weapon:'BASALT MAUL',ability:'Aegis — brace and taunt nearby foes.'}];
const ups=[
{id:'damage',icon:'✦',title:'Keen Edge',text:'Deal 20% more damage with every attack.'},
{id:'health',icon:'♡',title:'Second Wind',text:'Gain 35 max health and restore it fully.'},
{id:'speed',icon:'»',title:'Quick Hands',text:'Attack 18% faster. Every second counts.'},
{id:'boots',icon:'⌁',title:'Fleetfoot',text:'Move 14% faster through the fray.'},
{id:'vital',icon:'◉',title:'Vital Strike',text:'Gain 15% damage and 15 max health.'},
{id:'sword',classId:'melee',icon:'⚔',title:'Twin Fang',text:'Twin blades: +35% attack speed, −18% damage.'},
{id:'executioner',classId:'melee',icon:'✦',title:'Executioner',text:'Heavy hits deal 28% more damage.'},
{id:'whirlwind',classId:'melee',icon:'⟳',title:'Whirlwind Mastery',text:'Your spin strikes harder and returns sooner.'},
{id:'bloodletter',classId:'melee',icon:'♥',title:'Bloodletter',text:'Your blade steals a little life with each hit.'},
{id:'longbow',classId:'ranger',icon:'➶',title:'Farstrider Bow',text:'Longbow: +40% range and damage, −15% speed.'},
{id:'volley',classId:'ranger',icon:'⁙',title:'Arrowstorm',text:'Your Volley fires four additional arrows.'},
{id:'eagleeye',classId:'ranger',icon:'◎',title:'Eagle Eye',text:'Attack from farther away and hit 20% harder.'},
{id:'quickdraw',classId:'ranger',icon:'»',title:'Quickdraw',text:'Fire 25% faster with your bow.'},
{id:'charm',classId:'healer',icon:'✣',title:'Sunthread Charm',text:'Allies near you heal over time; +20 max health.'},
{id:'comfort',classId:'healer',icon:'✧',title:'Comforting Light',text:'Your healing aura reaches farther and heals more.'},
{id:'renewal',classId:'healer',icon:'✚',title:'Renewal',text:'Your class ability restores 15% more health.'},
{id:'medic',classId:'healer',icon:'♡',title:'Field Medic',text:'Gain 35 max health and restore it fully.'},
{id:'heavy',classId:'tank',icon:'⬡',title:'Stonebreaker',text:'Heavy maul: +35% damage, −20% attack speed.'},
{id:'fortress',classId:'tank',icon:'▣',title:'Living Fortress',text:'Gain 40 max health and restore it fully.'},
{id:'thorns',classId:'tank',icon:'✣',title:'Thornplate',text:'Strike enemies back when they hurt you.'},
{id:'aegis',classId:'tank',icon:'◈',title:'Lasting Aegis',text:'Your shield lasts longer and returns sooner.'}
];
const weaponDrops={melee:[{id:'warhammer',name:'WARHAMMER',icon:'⚒',damage:1.45,rate:.75,description:'+45% damage, −25% attack speed'},{id:'twinblades',name:'TWINBLADES',icon:'⚔',damage:.78,rate:1.4,description:'+40% attack speed, −22% damage'}],ranger:[{id:'stormstring',name:'STORMSTRING',icon:'ϟ',damage:.82,rate:1.18,lightning:true,description:'Lightning arrows chain to a nearby foe; +18% speed, −18% damage'},{id:'longshot',name:'LONGBOW',icon:'➶',damage:1.45,rate:.75,rangeBonus:80,description:'+45% damage and range, −25% attack speed'}],healer:[{id:'sunstaff',name:'SUNSTAFF',icon:'✹',damage:1.4,rate:.78,description:'+40% projectile damage, −22% attack speed'},{id:'bloomstaff',name:'BLOOM STAFF',icon:'✣',damage:.82,rate:1.15,healBonus:1.5,description:'+50% healing aura, +15% speed, −18% damage'}],tank:[{id:'grandmaul',name:'GRAND MAUL',icon:'⬡',damage:1.5,rate:.72,description:'+50% damage, −28% attack speed'},{id:'guardianflail',name:'GUARDIAN FLAIL',icon:'⛓',damage:.82,rate:1.25,description:'+25% attack speed, −18% damage'}]};
const partyColors=['#e8a55a','#64c4df','#d779cf','#9bc79a','#f07168','#b5a7ed','#d4ce67','#e2a678'];let activeRoomCode='';function assignPartyColors(){if(game)game.players.forEach((p,i)=>p.color=partyColors[i%partyColors.length])}let selected='melee',mode='solo',peer=null,hostConn=null,conns=[],activeConns={},remoteInputs={},game=null,raf=0,lastTime=0,keys={},touch=null,toastTimer=0,ending=false;const canvas=$('#arena'),ctx=canvas.getContext('2d');
function renderClasses(){ $('#classes').innerHTML=classes.map(c=>`<button class="class-card ${c.id===selected?'selected':''}" data-class="${c.id}"><div class="class-top"><span class="class-icon" style="color:${c.color}">${c.icon}</span><div><h3>${c.name}</h3><div class="class-role">${c.role}</div></div></div><p>${c.desc}</p><small class="class-passive"><b>PASSIVE</b> · ${c.passive}</small></button>`).join('');$('#classes').querySelectorAll('button').forEach(b=>b.onclick=()=>{selected=b.dataset.class;renderClasses()}) }
renderClasses();
function net(text,good=true){$('#netText').textContent=text;$('#netDot').style.background=good?'var(--green)':'var(--red)'}
function setMode(m){mode=m;document.querySelectorAll('.room-button').forEach(b=>b.classList.toggle('active',b.id===({solo:'soloBtn',host:'hostBtn',join:'joinBtn'}[m])));let p=$('#roomPanel');p.classList.toggle('hidden',m==='solo');p.innerHTML=m==='host'?`<div>ROOM CODE <span class="room-code" id="roomCode">----</span></div><p id="roomMsg">Opening your private room…</p>`:m==='join'?`<input id="codeInput" maxlength="6" placeholder="ENTER 6-LETTER CODE" autocomplete="off"><p id="roomMsg">Ask your host for their room code.</p>`:'';$('#startBtn').textContent=m==='host'?'OPEN THE GATES →':'BEGIN YOUR RUN →';net(m==='solo'?'SOLO MODE':m==='host'?'CREATING ROOM':'READY TO JOIN')}
$('#soloBtn').onclick=()=>setMode('solo');$('#hostBtn').onclick=()=>{setMode('host');createRoom()};$('#joinBtn').onclick=()=>{setMode('join');$('#codeInput').focus()};
const code=()=>Array.from(crypto.getRandomValues(new Uint8Array(6)),n=>'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[n%32]).join('');
function createRoom(){if(!window.Peer){$('#roomMsg').textContent='Multiplayer service didn’t load. Check your connection.';return}if(peer)peer.destroy();const room=code();peer=new Peer('emberfall-'+room.toLowerCase(),{debug:0});peer.on('open',()=>{activeRoomCode=room;$('#roomCode').textContent=room;$('#roomMsg').textContent='Share this code. Friends can join before or during the run.';net('ROOM '+room)});peer.on('connection',c=>{let registered=false;c.on('open',()=>{const key=c.metadata?.reconnectKey||'',cl=classes.find(x=>x.id===c.metadata?.classId)||classes[0];let p=key&&game?.players?.find(x=>x.reconnectKey===key),waiting=key&&waitingPlayers.find(x=>x.reconnectKey===key);if(ending){c.send({type:'ended',wave:game?.wave||0,kills:game?.kills||0});c.close();return}if(!p&&!waiting&&game?.players?.length>=8){c.send({type:'full'});c.close();return}if(p){p.disconnected=false;p.alive=true;p.hp=Math.max(1,p.hp);c.playerId=p.id}else if(waiting){waiting.conn=c;c.playerId=waiting.id}else{c.playerId='p'+Math.random().toString(36).slice(2,8);if(game){const anchor=game.players.find(q=>q.alive&&!q.disconnected),angle=Math.random()*Math.PI*2;p=makePlayer(c.playerId,cl,anchor?anchor.x+Math.cos(angle)*36:480,anchor?anchor.y+Math.sin(angle)*36:310);p.reconnectKey=key;p.disconnected=false;game.players.push(p);assignPartyColors();showToast(cl.name+' joined the run!')}else waitingPlayers.push({id:c.playerId,cl,conn:c,reconnectKey:key})}registered=true;activeConns[c.playerId]=c;c.send({type:'welcome',id:c.playerId,players:game?.players||[],started:!!game,state:game||null});if(game)syncParty();net('ROOM • '+(game?.players?.length||waitingPlayers.length+1)+' PLAYERS')});c.on('data',d=>{if(d.type==='input')remoteInputs[c.playerId]=d;if(d.type==='upgrade'&&game?.upgradePending)chooseUpgrade(d.id);if(d.type==='leave')removePlayer(c.playerId)});c.on('close',()=>{if(registered&&activeConns[c.playerId]===c){delete activeConns[c.playerId];removePlayer(c.playerId)}conns=conns.filter(x=>x!==c)}) ;conns.push(c)});peer.on('error',e=>{$('#roomMsg').textContent=e.type==='unavailable-id'?'Room code collision. Choose Host a room again.':'Could not open room. Check your internet connection.';net('ROOM ERROR',false)})}
let waitingPlayers=[];
function removePlayer(id){remoteInputs[id]=null;const p=game?.players?.find(x=>x.id===id);if(p){p.disconnected=true;syncParty()}const waiting=waitingPlayers.find(x=>x.id===id);if(waiting)waitingPlayers=waitingPlayers.filter(x=>x!==waiting)}
function connectRoom(){let room=$('#codeInput').value.toUpperCase().replace(/[^A-Z0-9]/g,'');if(room.length<4){$('#roomMsg').textContent='Enter the room code from your host.';return}if(!window.Peer){$('#roomMsg').textContent='Multiplayer service didn’t load. Check your connection.';return}if(peer)peer.destroy();peer=new Peer();activeRoomCode=room;let reconnectKey=sessionStorage.getItem('emberfall-rejoin-'+room);if(!reconnectKey){reconnectKey=crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2)+Date.now().toString(36);sessionStorage.setItem('emberfall-rejoin-'+room,reconnectKey)}peer.on('open',()=>{hostConn=peer.connect('emberfall-'+room.toLowerCase(),{metadata:{classId:selected,reconnectKey},reliable:true});hostConn.on('open',()=>{$('#roomMsg').textContent='Connected! Rejoin with this same code if disconnected.';net('CONNECTED • '+room);hostConn.on('data',handleClientMessage)});hostConn.on('error',()=>{$('#roomMsg').textContent='Could not join. Check the code and try again.';net('CONNECTION FAILED',false)});hostConn.on('close',()=>{if(mode==='join'&&game){game=null;$('#gameScreen').classList.add('hidden');$('#menuScreen').classList.remove('hidden');$('#roomPanel').classList.remove('hidden');$('#roomMsg').textContent='Disconnected. Enter the same room code and press Begin Your Run to rejoin.';net('DISCONNECTED',false)}})});peer.on('error',()=>{$('#roomMsg').textContent='Could not connect to that room. Check the code.';net('CONNECTION FAILED',false)})}
function makePlayer(id,cl,x,y){return{id,classId:cl.id,name:cl.name,hp:cl.hp,maxHp:cl.hp,x:x??480+(Math.random()-.5)*70,y:y??310+(Math.random()-.5)*70,speed:cl.speed,damage:cl.damage,rate:cl.rate,weapon:cl.weapon,weaponId:null,weaponDamageMod:1,weaponRateMod:1,weaponRangeBonus:0,alive:true,disconnected:false,level:1,xp:0,xpNext:50,abilityCd:0,abilityMax:cl.id==='healer'?12:10,invuln:0,shield:0,mods:{},attack:0,passiveStacks:0,passiveTimer:0,shotCount:0,reviveProgress:0,color:cl.color,aim:0}}
function start(){if(mode==='join'){if(!hostConn){connectRoom();return}return}if(mode==='host'&&!peer?.id){$('#roomMsg').textContent='Your room is still opening…';return}$('#menuScreen').classList.add('hidden');$('#gameScreen').classList.remove('hidden');resize();const cl=classes.find(x=>x.id===selected);game={players:[makePlayer('local',cl)],enemies:[],orbs:[],shots:[],effects:[],pickups:[],hearts:[],collectingOrbs:false,waveOrbXP:0,wave:0,timer:0,spawned:0,quota:0,breakTime:1.4,started:false,boss:false,kills:0,upgradePending:false,pendingOptions:null};waitingPlayers.forEach(x=>{const p=makePlayer(x.id,x.cl);p.reconnectKey=x.reconnectKey;game.players.push(p)});assignPartyColors();waitingPlayers.forEach(x=>x.conn.send({type:'begin',id:x.id,state:game}));waitingPlayers=[];if(mode==='host')net('ROOM LIVE');else net('SOLO MODE');updateHud();raf=requestAnimationFrame(loop)}
$('#startBtn').onclick=start;
function handleClientMessage(d){if(d.type==='full'){$('#roomMsg').textContent='This room is full (8 players).';return}if(d.type==='welcome'){clientId=d.id;game=d.started?d.state:null;if(game)showGame();return}if(d.type==='begin'){clientId=d.id;game=d.state;showGame();return}if(d.type==='state'){game=d.state;showGame();draw();updateHud();if(game.upgradePending&&$('#modal').classList.contains('hidden'))showUpgrade(game.players.find(p=>p.id===clientId)||game.players[0]);return}if(d.type==='toast')showToast(d.text);if(d.type==='ended')showResult(d.wave,d.kills)}let clientId=null;
function showGame(){if(!game)return;$('#menuScreen').classList.add('hidden');$('#gameScreen').classList.remove('hidden');resize();net('CONNECTED • LIVE');updateHud()}
function showToast(t){let el=$('#toast');el.textContent=t;el.classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.add('hidden'),1800)}
function syncParty(){if(mode==='host')conns.forEach(c=>{if(c.open)c.send({type:'state',state:game})});updateHud()}
function startWave(){game.wave++;game.started=true;game.timer=0;game.spawned=0;game.kills=0;game.boss=game.wave%5===0;const partySize=Math.max(1,game.players.length);game.quota=game.boss?1:Math.min(Math.round((5+game.wave*1.4)*(1+.3*(partySize-1))),45);game.breakTime=0;game.enemies=[];game.orbs=[];game.collectingOrbs=false;game.waveOrbXP=0;if(game.boss){let e=makeEnemy(true);game.enemies.push(e);game.spawned=1;showToast('BOSS WAVE '+String(game.wave).padStart(2,'0')+' — '+bossName(e.type).toUpperCase()+' APPROACHES')}else showToast('WAVE '+String(game.wave).padStart(2,'0')+' — HOLD THE LINE');updateHud()}
function rollEnemyType(){let choices=[['goblin',1.2]];if(game.wave>=3)choices.push(['ogre',.35+(game.wave-3)*.08]);if(game.wave>=7)choices.push(['demon',.2+(game.wave-7)*.08]);if(game.wave>=12)choices.push(['angel',.15+(game.wave-12)*.07]);let total=choices.reduce((n,x)=>n+x[1],0),pick=Math.random()*total;for(const [name,weight] of choices){pick-=weight;if(pick<=0)return name}return'angel'}
function rollBossType(){return['spider','clone','ogre','goblin','demon','angel'][Math.floor(Math.random()*6)]}
function bossName(type){return({spider:'Giant Spider',clone:'Player Echo',ogre:'Giant Ogre',goblin:'Giant Goblin',demon:'Giant Demon',angel:'Giant Angel'})[type]||'Boss'}
function makeEnemy(boss=false,forcedType=null){let angle=Math.random()*Math.PI*2,r=450+Math.random()*100;const partySize=Math.max(1,game.players.length),healthScale=1+.2*(partySize-1),damageScale=1+.12*(partySize-1),type=boss?(forcedType||rollBossType()):(forcedType||rollEnemyType()),tiers=boss?{spider:{hp:1.15,damage:1.2,speed:.9,size:1.8},clone:{hp:1.1,damage:1.25,speed:1,size:1},goblin:{hp:.9,damage:1.1,speed:1.05,size:1.8},ogre:{hp:1.25,damage:1.4,speed:.72,size:2},demon:{hp:1.35,damage:1.45,speed:.95,size:1.8},angel:{hp:1.5,damage:1.3,speed:.9,size:1.9}}[type]:{goblin:{hp:.85,damage:.85,speed:1.12,size:.86},ogre:{hp:1.8,damage:1.65,speed:.7,size:1.42},demon:{hp:3.1,damage:2.15,speed:1.02,size:1.08},angel:{hp:4.2,damage:2.6,speed:1.08,size:1.2}}[type],exemplar=boss&&type==='clone'?game.players[Math.floor(Math.random()*game.players.length)]:null;let hp=(boss?420:34)*(1+game.wave*.24)*healthScale*tiers.hp,damage=(boss?26:8+game.wave*.8)*damageScale*tiers.damage;return{id:Math.random().toString(36).slice(2),type,cloneClass:exemplar?.classId,cloneColor:exemplar?.color,cloneName:exemplar?.name,x:480+Math.cos(angle)*r,y:300+Math.sin(angle)*r,hp,maxHp:hp,speed:(boss?35:55+Math.random()*30)*(1+game.wave*.025)*tiers.speed,damage,radius:(boss?28:10+Math.min(5,game.wave*.2))*tiers.size,boss,attack:0,cloneAbilityCd:4,cloneShield:0,healCd:1.5+Math.random()*2}}
function damagePlayer(p,n){p.hp-=n;p.invuln=.2;if(p.hp<=0){p.hp=0;p.alive=false;p.reviveProgress=0;showToast(p.name+' is down — stand over them to revive!')}}
function updateCloneEnemy(e,target,d,dt){const cl=e.cloneClass||'melee',ranged=cl==='ranger'||cl==='healer',range=cl==='ranger'?245:cl==='healer'?185:0;e.attack-=dt;e.cloneAbilityCd-=dt;e.cloneShield=Math.max(0,(e.cloneShield||0)-dt);if(ranged){if(d>range+24){e.x+=(target.x-e.x)/d*e.speed*dt;e.y+=(target.y-e.y)/d*e.speed*dt}else if(d<range-35){e.x-=(target.x-e.x)/d*e.speed*dt;e.y-=(target.y-e.y)/d*e.speed*dt}if(e.attack<=0){e.attack=cl==='ranger'?.82:1.05;const n=d||1;game.shots.push({x:e.x,y:e.y,vx:(target.x-e.x)/n*(cl==='ranger'?340:270),vy:(target.y-e.y)/n*(cl==='ranger'?340:270),damage:e.damage*(cl==='ranger'?.58:.42),life:2.2,team:'enemy',kind:cl==='ranger'?'cloneArrow':'ember'})}}else if(d>e.radius+15){e.x+=(target.x-e.x)/d*e.speed*dt;e.y+=(target.y-e.y)/d*e.speed*dt}else if(e.attack<=0){e.attack=cl==='tank'?1.05:.86;damagePlayer(target,e.damage*(cl==='tank'?1.12:.78)*damageMultiplier(target))}if(e.cloneAbilityCd<=0){e.cloneAbilityCd=cl==='melee'?7:cl==='ranger'?8:cl==='healer'?8:10;if(cl==='melee'){game.players.filter(p=>p.alive&&dist(p,e)<100).forEach(p=>damagePlayer(p,e.damage*.7*damageMultiplier(p)));game.effects.push({x:e.x,y:e.y,r:100,color:e.cloneColor||'#e8a55a',life:.42,ring:true})}else if(cl==='ranger'){for(let i=0;i<8;i++){let a=i*Math.PI/4;game.shots.push({x:e.x,y:e.y,vx:Math.cos(a)*270,vy:Math.sin(a)*270,damage:e.damage*.32,life:1.6,team:'enemy',kind:'cloneArrow'})}}else if(cl==='healer'){game.enemies.filter(a=>a!==e&&a.hp>0&&dist(a,e)<150&&a.hp<a.maxHp).forEach(a=>a.hp=Math.min(a.maxHp,a.hp+a.maxHp*.2));game.effects.push({x:e.x,y:e.y,r:145,color:'#f2d78a',life:.45,ring:true})}else{e.cloneShield=4;game.effects.push({x:e.x,y:e.y,r:34,color:e.cloneColor||'#a99ad7',life:.5,ring:true})}}}
function animateExperienceOrbs(dt){if(!game.collectingOrbs)return;game.orbs.forEach(o=>{let p=game.players.find(q=>q.id===o.targetId&&q.alive&&!q.disconnected)||game.players.filter(q=>q.alive&&!q.disconnected).sort((a,b)=>dist(a,o)-dist(b,o))[0];if(!p){o.collected=true;return}o.targetId=p.id;let dx=p.x-o.x,dy=p.y-o.y,d=Math.hypot(dx,dy),step=420*dt;if(d<=step+10){o.collected=true;game.effects.push({x:p.x,y:p.y,r:12,color:'#83d5e3',life:.18})}else{o.x+=dx/d*step;o.y+=dy/d*step}});game.orbs=game.orbs.filter(o=>!o.collected)}
function loop(ts){if(!game||mode==='join'){raf=requestAnimationFrame(loop);return}let dt=Math.min(.035,(ts-lastTime)/1000||.016);lastTime=ts;tick(dt);draw();updateHud();if(game&&!ending)raf=requestAnimationFrame(loop)}
function tick(dt){if(game.upgradePending)return;game.timer+=dt;game.players.forEach(p=>{if(!p.alive||p.disconnected)return;let input=p.id==='local'?{x:(keys.d?1:0)-(keys.a?1:0),y:(keys.s?1:0)-(keys.w?1:0),ability:keys[' ']}:remoteInputs[p.id]||{};let x=input.x||0,y=input.y||0;if(touch&&p.id==='local'){x=touch.x;y=touch.y}let m=Math.hypot(x,y)||1;p.x+=x/m*p.speed*dt;p.y+=y/m*p.speed*dt;p.x=Math.max(25,Math.min(935,p.x));p.y=Math.max(25,Math.min(575,p.y));p.invuln=Math.max(0,p.invuln-dt);p.abilityCd=Math.max(0,p.abilityCd-dt);p.attack-=dt;p.passiveTimer=Math.max(0,p.passiveTimer-dt);if(p.passiveTimer<=0)p.passiveStacks=0;if(input.ability&&p.abilityCd<=0)useAbility(p);if(p.classId==='healer')game.players.filter(q=>q.alive&&!q.disconnected&&Math.hypot(q.x-p.x,q.y-p.y)<(p.mods.comfort?140:100)).forEach(q=>q.hp=Math.min(q.maxHp,q.hp+(2+(p.mods.comfort?3:0)+(p.weaponHealBonus||0))*dt));if(p.attack<=0){const target=game.enemies.filter(e=>e.hp>0).sort((a,b)=>dist(p,a)-dist(p,b))[0];if(target&&dist(p,target)<((p.mods.range||((p.classId==='ranger'||p.classId==='healer')?350:p.classId==='melee'?55:70))+(p.weaponRangeBonus||0))){attack(p,target);p.attack=1/(p.rate*(p.classId==='melee'?1+p.passiveStacks*.05:1))}}});processRevives(dt);collectWeaponPickups();
if(game.breakTime>0){game.breakTime-=dt;if(game.breakTime<=0)startWave();return}if(!game.boss&&game.spawned<game.quota&&game.timer>(game.spawned===0?0:Math.max(.2,1.05-game.wave*.025))){game.enemies.push(makeEnemy());game.spawned++}
game.shots.forEach(s=>{s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;if(s.team==='enemy'){let p=game.players.find(p=>p.alive&&dist(s,p)<15);if(p){damagePlayer(p,s.damage*damageMultiplier(p));s.life=0}}else{let e=game.enemies.find(e=>e.hp>0&&dist(s,e)<e.radius+7);if(e){hit(e,s.damage,s.owner);if(s.lightning||s.kind==='lightningArrow'){let chain=game.enemies.find(a=>a.hp>0&&a!==e&&dist(a,e)<105);if(chain){hit(chain,s.damage*.5,s.owner);game.effects.push({x:chain.x,y:chain.y,r:18,color:'#7fe8ff',life:.2})}}s.life=0}}});game.shots=game.shots.filter(s=>s.life>0);
game.enemies.forEach(e=>{if(e.hp<=0)return;let targets=game.players.filter(p=>p.alive&&!p.disconnected);if(!targets.length)return;let target=targets.sort((a,b)=>dist(a,e)-dist(b,e))[0],d=dist(e,target);if(e.type==='angel'){e.healCd-=dt;if(e.healCd<=0){game.enemies.filter(a=>a!==e&&a.hp>0&&dist(a,e)<155&&a.hp<a.maxHp).forEach(a=>{a.hp=Math.min(a.maxHp,a.hp+a.maxHp*.14)});game.effects.push({x:e.x,y:e.y,r:150,color:'#f2d78a',life:.45,ring:true});e.healCd=5}}if(e.type==='clone'){updateCloneEnemy(e,target,d,dt)}else if(e.type==='demon'){let range=225;if(d>range+20){e.x+=(target.x-e.x)/d*e.speed*dt;e.y+=(target.y-e.y)/d*e.speed*dt}else if(d<range-40){e.x-=(target.x-e.x)/d*e.speed*dt;e.y-=(target.y-e.y)/d*e.speed*dt}e.attack-=dt;if(e.attack<=0){e.attack=1.65;let n=d||1;game.shots.push({x:e.x,y:e.y,vx:(target.x-e.x)/n*220,vy:(target.y-e.y)/n*220,damage:e.damage,life:2.2,team:'enemy',kind:'ember'})}}else if(d>e.radius+12){e.x+=(target.x-e.x)/d*e.speed*dt;e.y+=(target.y-e.y)/d*e.speed*dt}else{e.attack-=dt;if(e.attack<=0){e.attack=e.boss?1:.85;let reduction=damageMultiplier(target);damagePlayer(target,e.damage*reduction);if(target.mods.thorns)e.hp-=e.damage*target.mods.thorns}}});
resolveEnemyCollisions();
game.enemies=game.enemies.filter(e=>{if(e.hp>0)return true;game.kills++;game.orbs.push({x:e.x,y:e.y,r:e.boss?9:5,value:e.boss?120:10,phase:Math.random()*8});game.hearts||=[];if(Math.random()<.05)game.hearts.push({x:e.x,y:e.y,r:9,phase:Math.random()*8});if(e.boss){showToast('BOSS FALLEN — WEAPONS DROPPED!');let living=game.players.filter(p=>p.alive);living.forEach((p,i)=>dropWeapon(p,e.x+Math.cos(i*6.28/Math.max(1,living.length))*(e.radius+24),e.y+Math.sin(i*6.28/Math.max(1,living.length))*(e.radius+24)))}else if(Math.random()<.025){let living=game.players.filter(p=>p.alive);if(living.length){let p=living[Math.floor(Math.random()*living.length)];dropWeapon(p,e.x,e.y)}}return false});game.orbs.forEach(o=>o.phase+=dt*2);animateExperienceOrbs(dt);game.hearts||=[];game.hearts.forEach(h=>h.phase+=dt*4);collectHealingHearts();
if(game.spawned>=game.quota&&!game.enemies.length){if(game.orbs.length&&!game.collectingOrbs){game.collectingOrbs=true;game.waveOrbXP=game.orbs.reduce((sum,o)=>sum+o.value,0);showToast('EXPERIENCE ORBS RETURNING TO THE PARTY');syncParty()}if(game.orbs.length)return;let alive=game.players.filter(p=>p.alive);if(game.waveOrbXP){alive.forEach(p=>gainXP(p,game.waveOrbXP/Math.max(1,alive.length)));game.waveOrbXP=0;game.collectingOrbs=false}if(!alive.length){finish(false);return}let up=alive.find(p=>p.xp>=p.xpNext);if(up){game.upgradePending=true;showUpgrade(up);syncParty()}else{game.breakTime=3;showToast('WAVE CLEARED — REST UP');syncParty()}}
if(game.players.every(p=>!p.alive)){finish(false);return}}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function resolveEnemyCollisions(){const enemies=game.enemies.filter(e=>e.hp>0);for(let pass=0;pass<2;pass++){for(let i=0;i<enemies.length;i++)for(let j=i+1;j<enemies.length;j++){let a=enemies[i],b=enemies[j],dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy),min=a.radius+b.radius;if(d<min){if(d<.001){dx=.01;dy=0;d=.01}let push=(min-d)/2,px=dx/d*push,py=dy/d*push;a.x-=px;a.y-=py;b.x+=px;b.y+=py}}for(const e of enemies)for(const p of game.players){if(!p.alive)continue;let dx=e.x-p.x,dy=e.y-p.y,d=Math.hypot(dx,dy),min=e.radius+12;if(d<min){if(d<.001){dx=1;dy=0;d=1}let push=min-d;e.x+=dx/d*push;e.y+=dy/d*push}}for(const e of enemies){e.x=Math.max(e.radius,Math.min(960-e.radius,e.x));e.y=Math.max(e.radius,Math.min(600-e.radius,e.y))}}}
function gainXP(p,n){p.xp+=n}
function attack(p,e){let cl=p.classId;if(cl==='ranger'||cl==='healer'){let d=dist(p,e)||1,speed=cl==='ranger'?460:330,critical=false;if(cl==='ranger'){p.shotCount=(p.shotCount||0)+1;critical=p.shotCount%4===0}game.shots.push({x:p.x,y:p.y,vx:(e.x-p.x)/d*speed,vy:(e.y-p.y)/d*speed,damage:p.damage*(critical?3:1),owner:p.id,lightning:cl==='ranger'&&p.weaponId==='stormstring',life:1.4,kind:critical?'critArrow':cl==='ranger'?(p.weaponId==='stormstring'?'lightningArrow':'arrow'):'mote'});game.effects.push({x:p.x,y:p.y,r:7,color:critical?'#ffe18b':p.color,life:.14})}else{let d=dist(p,e);if(d<=(p.classId==='melee'?55:82)){hit(e,p.damage,p.id);game.effects.push({x:e.x,y:e.y,r:24,color:p.color,life:.2})}}}
function hit(e,n,owner){let attacker=owner?game.players.find(x=>x.id===owner):null,wasAlive=e.hp>0;if(e.type==='clone'&&e.cloneShield>0)n*=.45;e.hp-=n;if(attacker?.mods.bloodletter)attacker.hp=Math.min(attacker.maxHp,attacker.hp+attacker.maxHp*.012);if(e.hp<=0){e.hp=0;if(wasAlive&&attacker?.classId==='melee'){attacker.passiveStacks=Math.min(4,attacker.passiveStacks+1);attacker.passiveTimer=5}}game.effects.push({x:e.x,y:e.y,r:12,color:e.boss?'#ee735f':'#e7b469',life:.12})}
function damageMultiplier(p){let scale=p.shield>0?.3:1;if(game.players.some(q=>q.alive&&q.classId==='tank'&&dist(q,p)<115))scale*=.85;return scale}function processRevives(dt){for(const down of game.players.filter(p=>!p.alive)){let rescuer=game.players.find(p=>p.alive&&p.id!==down.id&&dist(p,down)<36);if(rescuer){down.reviveProgress=Math.min(5,(down.reviveProgress||0)+dt);down.reviveBy=rescuer.id;if(down.reviveProgress>=5){down.alive=true;down.hp=Math.max(1,down.maxHp*.35);down.invuln=2;down.reviveProgress=0;showToast(down.name+' is back in the fight!')}}else down.reviveProgress=Math.max(0,(down.reviveProgress||0)-dt)}}
function dropWeapon(p,x,y){let list=weaponDrops[p.classId],item=list[Math.floor(Math.random()*list.length)];game.pickups.push({x,y,classId:p.classId,item:{...item},phase:Math.random()*6})}
function applyWeaponPickup(p,item){p.damage*=item.damage/(p.weaponDamageMod||1);p.rate*=item.rate/(p.weaponRateMod||1);p.weaponDamageMod=item.damage;p.weaponRateMod=item.rate;p.weaponRangeBonus=item.rangeBonus||0;p.weaponHealBonus=item.healBonus||0;p.weaponId=item.id;p.weapon=item.name;showToast(p.name+' picked up '+item.name+'!')}
function collectWeaponPickups(){for(let i=game.pickups.length-1;i>=0;i--){let w=game.pickups[i],p=game.players.find(p=>p.alive&&p.classId===w.classId&&dist(p,w)<27);if(p){applyWeaponPickup(p,w.item);game.pickups.splice(i,1)}}}
function collectHealingHearts(){for(let i=game.hearts.length-1;i>=0;i--){let h=game.hearts[i],p=game.players.find(p=>p.alive&&!p.disconnected&&p.hp<p.maxHp&&dist(p,h)<25);if(p){let heal=Math.min(p.maxHp-p.hp,p.maxHp*.3);p.hp=Math.min(p.maxHp,p.hp+p.maxHp*.3);game.effects.push({x:p.x,y:p.y,r:23,color:'#ff7180',life:.3,ring:true});game.hearts.splice(i,1);showToast(heal>0?'HEALING HEART — RESTORED HEALTH':'HEALING HEART — HEALTH FULL')}}}
function useAbility(p){p.abilityCd=p.abilityMax;let c=p.classId;if(c==='melee'){game.enemies.forEach(e=>{if(dist(e,p)<115)hit(e,p.damage*(1+(p.mods.abilityPower||0)),p.id)});game.effects.push({x:p.x,y:p.y,r:115,color:p.color,life:.4,ring:true})}else if(c==='ranger'){for(let i=0;i<12+(p.mods.volley||0);i++){let a=i/(12+(p.mods.volley||0))*Math.PI*2;game.shots.push({x:p.x,y:p.y,vx:Math.cos(a)*300,vy:Math.sin(a)*300,damage:p.damage*.9,owner:p.id,life:1.2,kind:'arrow'})}}else if(c==='healer'){game.players.filter(q=>q.alive&&dist(p,q)<180).forEach(q=>q.hp=Math.min(q.maxHp,q.hp+q.maxHp*(.32+(p.mods.renewal||0))));game.effects.push({x:p.x,y:p.y,r:180,color:p.color,life:.55,ring:true})}else{p.shield=4+(p.mods.aegis?2:0);game.enemies.forEach(e=>{if(dist(e,p)<190)e.taunt=3});game.effects.push({x:p.x,y:p.y,r:190,color:p.color,life:.55,ring:true})}showToast(classes.find(x=>x.id===c).ability.split(' —')[0]+'!')}
function shuffle(items){return [...items].sort(()=>Math.random()-.5)}
function buildUpgradeOptions(classId){return [...shuffle(ups.filter(u=>u.classId===classId)).slice(0,2),...shuffle(ups.filter(u=>!u.classId)).slice(0,1)]}
function showUpgrade(p){if(!game.pendingOptions&&mode!=='join')game.pendingOptions=buildUpgradeOptions(p.classId);let options=game.pendingOptions||buildUpgradeOptions(p.classId);$('#modal').classList.remove('hidden');$('#modalEyebrow').textContent='LEVEL '+String(p.level+1).padStart(2,'0')+' — A MOMENT OF CHOICE';$('#modalTitle').textContent=p.name+' grows stronger';$('#modalSub').textContent='Choose a shared boon or follow your class’s upgrade path.';$('#upgradeCards').innerHTML=options.map(u=>`<button class="upgrade-card" data-up="${u.id}"><span class="upgrade-icon">${u.icon}</span><h3>${u.title}</h3><p>${u.text}</p></button>`).join('');$('#upgradeCards').querySelectorAll('button').forEach(b=>b.onclick=()=>{if(mode==='join'){hostConn?.send({type:'upgrade',id:b.dataset.up});$('#modal').classList.add('hidden')}else chooseUpgrade(b.dataset.up)})}
function chooseUpgrade(id){if(!game?.upgradePending)return;let u=ups.find(x=>x.id===id);if(!u||!game.pendingOptions?.some(x=>x.id===id))return;game.players.filter(p=>p.alive).forEach(p=>{p.level++;p.xp-=p.xpNext;p.xpNext=Math.round(p.xpNext*1.42);applyUpgrade(p,id)});game.upgradePending=false;game.pendingOptions=null;$('#modal').classList.add('hidden');showToast(u.title+' — '+u.text);if(game.players.some(p=>p.alive&&p.xp>=p.xpNext)){let p=game.players.find(p=>p.alive&&p.xp>=p.xpNext);game.upgradePending=true;showUpgrade(p);syncParty()}else{game.breakTime=3;syncParty()}}
function applyUpgrade(p,id){let u=ups.find(x=>x.id===id);if(u?.classId&&u.classId!==p.classId)return;p.mods[id]=(p.mods[id]||0)+1;if(id==='damage')p.damage*=1.2;if(id==='health'||id==='medic'||id==='fortress'){let n=id==='fortress'?40:35;p.maxHp+=n;p.hp=Math.min(p.maxHp,p.hp+n)}if(id==='speed')p.rate*=1.18;if(id==='boots')p.speed*=1.14;if(id==='vital'){p.damage*=1.15;p.maxHp+=15;p.hp+=15}if(id==='sword'){p.damage*=.82;p.rate*=1.35;p.weapon='TWIN FANGS'}if(id==='executioner')p.damage*=1.28;if(id==='whirlwind'){p.abilityMax=Math.max(4,p.abilityMax*.88);p.mods.abilityPower=(p.mods.abilityPower||0)+.35}if(id==='bloodletter')p.damage*=1.12;if(id==='heavy'){p.damage*=1.35;p.rate*=.8;p.weapon='STONEBREAKER'}if(id==='longbow'){p.damage*=1.4;p.rate*=.85;p.mods.range=440;p.weapon='FARSTRIDER BOW'}if(id==='volley')p.mods.volley=(p.mods.volley||0)+4;if(id==='eagleeye'){p.mods.range=480;p.damage*=1.2}if(id==='quickdraw')p.rate*=1.25;if(id==='charm'){p.maxHp+=20;p.hp+=20;p.weapon='SUNTHREAD CHARM'}if(id==='comfort')p.mods.comfort=(p.mods.comfort||0)+1;if(id==='renewal'){p.mods.renewal=(p.mods.renewal||0)+.15;p.abilityMax=Math.max(4,p.abilityMax*.9)}if(id==='fortress')p.damage*=1.08;if(id==='thorns')p.mods.thorns=(p.mods.thorns||0)+.3;if(id==='aegis'){p.mods.aegis=(p.mods.aegis||0)+1;p.abilityMax=Math.max(4,p.abilityMax*.85)}}
function finish(victory){if(ending)return;ending=true;if(mode==='host')conns.forEach(c=>c.send({type:'ended',wave:game.wave,kills:game.kills}));showResult(game.wave,game.kills,victory)}function showResult(w,k,v=false){ending=true;$('#resultTitle').textContent=v?'A legend is born.':'The light went out.';$('#resultText').textContent=`Your party survived ${w} wave${w===1?'':'s'} and defeated ${k} foes.`;$('#resultModal').classList.remove('hidden')}
$('#returnBtn').onclick=()=>{if(peer)peer.destroy();peer=null;hostConn=null;conns=[];activeConns={};waitingPlayers=[];game=null;ending=false;$('#resultModal').classList.add('hidden');$('#gameScreen').classList.add('hidden');$('#menuScreen').classList.remove('hidden');setMode('solo');net('SOLO MODE')};$('#leaveBtn').onclick=()=>finish(false);
function updateHud(){if(!game)return;let p=game.players.find(x=>x.id==='local')||game.players.find(x=>x.id===clientId)||game.players[0];if(!p)return;$('#waveNum').textContent=String(game.wave).padStart(2,'0');$('#bossTag').classList.toggle('hidden',!game.boss);$('#waveStatus').textContent=game.upgradePending?'LEVEL UP — CHOOSE YOUR GIFT':game.breakTime>0?'WAVE CLEARED — NEXT WAVE IN '+Math.ceil(game.breakTime):game.boss?'DEFEAT THE WARDEN':'SURVIVE THE NIGHT';$('#waveBar').style.width=game.quota?`${game.spawned/game.quota*100}%`:'0%';$('#partyNum').textContent=String(game.players.filter(x=>x.alive).length).padStart(2,'0');$('#playerName').textContent=p.name;$('#weaponName').textContent=p.weapon;$('#portrait').textContent=classes.find(c=>c.id===p.classId)?.icon||'✦';$('#portrait').style.color=p.color;$('#healthBar').style.width=(p.hp/p.maxHp*100)+'%';$('#xpBar').style.width=Math.min(100,p.xp/p.xpNext*100)+'%';$('#abilityBar').style.width=(Math.max(0,1-p.abilityCd/p.abilityMax)*100)+'%';$('#abilityText').textContent=p.abilityCd<=0?'ABILITY READY':'ABILITY · '+p.abilityCd.toFixed(1)+'s';$('#levelNum').textContent=String(p.level).padStart(2,'0');$('#teammates').innerHTML=game.players.filter(q=>q.id!=='local'&&q.alive).map(q=>`<div class="teammate"><i style="background:${q.color}"></i><span>${q.name} · ${q.hp|0} HP</span></div>`).join('')}
function resize(){let r=canvas.getBoundingClientRect(),d=window.devicePixelRatio||1;canvas.width=Math.max(1,Math.floor(r.width*d));canvas.height=Math.max(1,Math.floor(r.height*d));ctx.setTransform(canvas.width/960,0,0,canvas.height/600,0,0)}window.addEventListener('resize',resize);setTimeout(resize,100);
function drawPlayer(p){let phase=(game.timer*8+(p.id.charCodeAt(0)||0))%6.28,bob=Math.sin(phase)*1.2,cl=p.classId;ctx.save();ctx.translate(p.x,p.y);ctx.globalAlpha=p.alive?1:.35;ctx.fillStyle='#0008';ctx.beginPath();ctx.ellipse(0,10,15,6,0,0,Math.PI*2);ctx.fill();if(p.shield>0){ctx.strokeStyle=p.color;ctx.globalAlpha=.45;ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,22,0,Math.PI*2);ctx.stroke()}ctx.globalAlpha=p.alive?1:.35;ctx.translate(0,bob);let swing=Math.sin(game.timer*17)*.12;ctx.lineCap='round';ctx.lineJoin='round';
// Legs and class silhouette.
ctx.strokeStyle=cl==='tank'?'#302d40':'#292932';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(-5,5);ctx.lineTo(-6,12);ctx.moveTo(5,5);ctx.lineTo(6,12);ctx.stroke();ctx.fillStyle='#d3c7b6';ctx.fillRect(-10,10,7,3);ctx.fillRect(4,10,7,3);
if(cl==='melee'){ctx.fillStyle='#60412e';ctx.beginPath();ctx.moveTo(-9,-7);ctx.lineTo(9,-7);ctx.lineTo(12,8);ctx.lineTo(0,14);ctx.lineTo(-12,8);ctx.closePath();ctx.fill();ctx.fillStyle=p.color;ctx.fillRect(-9,-9,18,15);ctx.fillStyle='#e4b36a';ctx.fillRect(-7,-7,14,3);ctx.fillStyle='#edd4a5';ctx.beginPath();ctx.arc(0,-14,7,0,Math.PI*2);ctx.fill();ctx.fillStyle='#a96136';ctx.beginPath();ctx.moveTo(-7,-16);ctx.lineTo(-5,-23);ctx.lineTo(-1,-18);ctx.lineTo(3,-24);ctx.lineTo(7,-16);ctx.closePath();ctx.fill();ctx.strokeStyle='#dfc27e';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(9,-6);ctx.lineTo(17,-15+swing*14);ctx.stroke();ctx.strokeStyle='#e9e3d5';ctx.lineWidth=2.5;ctx.beginPath();ctx.moveTo(17,-15+swing*14);ctx.lineTo(22,-25+swing*14);ctx.stroke()}
else if(cl==='ranger'){ctx.fillStyle=p.color;ctx.beginPath();ctx.moveTo(-10,-8);ctx.lineTo(10,-8);ctx.lineTo(8,9);ctx.lineTo(0,14);ctx.lineTo(-8,9);ctx.closePath();ctx.fill();ctx.fillStyle='#74966a';ctx.beginPath();ctx.moveTo(-9,-14);ctx.lineTo(0,-25);ctx.lineTo(9,-14);ctx.lineTo(7,-5);ctx.lineTo(-7,-5);ctx.closePath();ctx.fill();ctx.fillStyle='#dec69a';ctx.beginPath();ctx.arc(0,-13,4,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#bc8a4b';ctx.lineWidth=2;ctx.beginPath();ctx.arc(-13,-5,11,-1.25,1.25);ctx.stroke();ctx.strokeStyle='#ddca9e';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(-17,-15);ctx.lineTo(-9,5);ctx.stroke();ctx.strokeStyle='#4b392b';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(6,-7);ctx.lineTo(13,-13);ctx.stroke()}
else if(cl==='healer'){ctx.fillStyle=p.color;ctx.beginPath();ctx.moveTo(-7,-9);ctx.lineTo(7,-9);ctx.lineTo(11,10);ctx.lineTo(0,14);ctx.lineTo(-11,10);ctx.closePath();ctx.fill();ctx.fillStyle='#75c3bd';ctx.beginPath();ctx.moveTo(-8,-12);ctx.lineTo(0,-23);ctx.lineTo(8,-12);ctx.closePath();ctx.fill();ctx.fillStyle='#f1d9a3';ctx.beginPath();ctx.arc(0,-13,4.5,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#e8ca82';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,-25,6,Math.PI,Math.PI*2);ctx.stroke();ctx.strokeStyle='#735c43';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(13,-18);ctx.lineTo(13,10);ctx.stroke();ctx.fillStyle='#d9f1d1';ctx.shadowColor='#93e6dd';ctx.shadowBlur=8;ctx.beginPath();ctx.arc(13,-19,4,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0}
else{ctx.fillStyle='#504963';ctx.beginPath();ctx.moveTo(-12,-8);ctx.lineTo(12,-8);ctx.lineTo(14,8);ctx.lineTo(0,14);ctx.lineTo(-14,8);ctx.closePath();ctx.fill();ctx.fillStyle=p.color;ctx.fillRect(-12,-9,24,14);ctx.fillStyle='#c4b3df';ctx.fillRect(-8,-7,16,3);ctx.fillStyle='#b1a0d0';ctx.beginPath();ctx.arc(0,-15,8,0,Math.PI*2);ctx.fill();ctx.fillStyle='#655b79';ctx.beginPath();ctx.moveTo(-8,-17);ctx.lineTo(-13,-23);ctx.lineTo(-4,-20);ctx.moveTo(8,-17);ctx.lineTo(13,-23);ctx.lineTo(4,-20);ctx.fill();ctx.fillStyle='#73638d';ctx.beginPath();ctx.moveTo(-11,-5);ctx.lineTo(-20,-9);ctx.lineTo(-21,3);ctx.lineTo(-15,9);ctx.lineTo(-9,5);ctx.closePath();ctx.fill();ctx.strokeStyle='#c5b7dc';ctx.lineWidth=2;ctx.stroke();ctx.strokeStyle='#513e33';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(12,-5);ctx.lineTo(18,-16+swing*10);ctx.stroke();ctx.strokeStyle='#b7a7c9';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(15,-16+swing*10);ctx.lineTo(21,-24+swing*10);ctx.stroke()}
 ctx.restore();ctx.save();ctx.globalAlpha=p.alive?1:.35;ctx.fillStyle='#f4ece1';ctx.font='10px Manrope';ctx.textAlign='center';if(p.alive)ctx.fillText(p.name,p.x,p.y-29);else{ctx.fillText(p.name,p.x,p.y-55);ctx.fillStyle='#d9c9ae';ctx.font='7px DM Mono';ctx.fillText('REVIVE '+(p.reviveProgress||0).toFixed(1)+' / 5s',p.x,p.y-44);ctx.fillStyle='#17151add';ctx.fillRect(p.x-23,p.y-39,46,5);ctx.fillStyle='#8ccbbb';ctx.fillRect(p.x-22,p.y-38,44*Math.min(1,(p.reviveProgress||0)/5),3)}ctx.restore()}
function drawEnemySprite(e){if(e.type==='clone'){let fake={id:e.id,name:(e.cloneName||'Player')+"’s Echo",x:e.x,y:e.y,classId:e.cloneClass||'melee',color:e.cloneColor||'#e8a55a',alive:true,shield:e.cloneShield||0};drawPlayer(fake);ctx.fillStyle='#ffffff30';ctx.fillRect(e.x-e.radius,e.y-e.radius-9,e.radius*2,3);ctx.fillStyle='#e978d7';ctx.fillRect(e.x-e.radius,e.y-e.radius-9,e.radius*2*Math.max(0,e.hp/e.maxHp),3);return}ctx.save();ctx.translate(e.x,e.y);let s=e.radius/11;ctx.scale(s,s);ctx.lineJoin='round';ctx.lineCap='round';if(e.type==='spider'){ctx.strokeStyle='#3d253b';ctx.lineWidth=3;for(let side of [-1,1])for(let i=0;i<4;i++){let y=-7+i*4;ctx.beginPath();ctx.moveTo(side*5,y);ctx.lineTo(side*(11+i),y-7);ctx.lineTo(side*(15+i),y+2);ctx.stroke()}ctx.fillStyle='#56354f';ctx.beginPath();ctx.ellipse(0,3,10,13,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#9d465a';ctx.beginPath();ctx.ellipse(0,-5,8,8,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ffbe78';ctx.beginPath();ctx.arc(-3,-6,1.8,0,Math.PI*2);ctx.arc(3,-6,1.8,0,Math.PI*2);ctx.fill()}else if(e.type==='goblin'){ctx.fillStyle='#567b4a';ctx.beginPath();ctx.moveTo(-5,-4);ctx.lineTo(-14,-11);ctx.lineTo(-10,-1);ctx.moveTo(5,-4);ctx.lineTo(14,-11);ctx.lineTo(10,-1);ctx.fill();ctx.fillStyle='#668a50';ctx.beginPath();ctx.ellipse(0,1,8,9,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#92ad62';ctx.beginPath();ctx.ellipse(0,-5,7,7,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#252523';ctx.fillRect(-4,-6,2,2);ctx.fillRect(3,-6,2,2);ctx.fillStyle='#e7d5a1';ctx.beginPath();ctx.moveTo(-2,-1);ctx.lineTo(0,2);ctx.lineTo(2,-1);ctx.fill();ctx.strokeStyle='#b9b5a3';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(8,2);ctx.lineTo(13,-5);ctx.stroke()}
else if(e.type==='ogre'){ctx.fillStyle='#594b42';ctx.beginPath();ctx.ellipse(0,2,13,12,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#8a7760';ctx.beginPath();ctx.ellipse(0,-5,10,9,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#302722';ctx.fillRect(-7,-8,5,2);ctx.fillRect(3,-8,5,2);ctx.fillStyle='#e9d8b7';ctx.beginPath();ctx.moveTo(-5,0);ctx.lineTo(-2,0);ctx.lineTo(-3,5);ctx.moveTo(5,0);ctx.lineTo(2,0);ctx.lineTo(3,5);ctx.fill();ctx.fillStyle='#a99474';ctx.fillRect(-16,-1,4,12);ctx.fillRect(12,-1,4,12)}
else if(e.type==='demon'){ctx.fillStyle='#512b34';ctx.beginPath();ctx.moveTo(-7,-2);ctx.lineTo(-16,-13);ctx.lineTo(-14,0);ctx.lineTo(-8,5);ctx.moveTo(7,-2);ctx.lineTo(16,-13);ctx.lineTo(14,0);ctx.lineTo(8,5);ctx.fill();ctx.fillStyle='#a34748';ctx.beginPath();ctx.ellipse(0,2,9,12,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#cf6553';ctx.beginPath();ctx.arc(0,-6,8,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ffd178';ctx.fillRect(-5,-8,3,2);ctx.fillRect(3,-8,3,2);ctx.strokeStyle='#9f4949';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(7,8);ctx.quadraticCurveTo(17,13,11,18);ctx.stroke()}
else{ctx.fillStyle='#f2dfad';ctx.beginPath();ctx.ellipse(-10,0,8,13,-.35,0,Math.PI*2);ctx.ellipse(10,0,8,13,.35,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff1ce';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,-14,5,Math.PI,Math.PI*2);ctx.stroke();ctx.fillStyle='#d5b76b';ctx.beginPath();ctx.moveTo(-7,-4);ctx.lineTo(7,-4);ctx.lineTo(9,11);ctx.lineTo(0,15);ctx.lineTo(-9,11);ctx.closePath();ctx.fill();ctx.fillStyle='#fff0c6';ctx.beginPath();ctx.arc(0,-8,7,0,Math.PI*2);ctx.fill();ctx.fillStyle='#9d6d38';ctx.fillRect(-4,-9,2,2);ctx.fillRect(3,-9,2,2)}ctx.restore();ctx.fillStyle='#ffffff27';ctx.fillRect(e.x-e.radius,e.y-e.radius-9,e.radius*2,3);ctx.fillStyle=e.type==='goblin'?'#a1ca68':e.type==='ogre'?'#c0a078':e.type==='demon'?'#ed7466':'#f2d78a';ctx.fillRect(e.x-e.radius,e.y-e.radius-9,e.radius*2*Math.max(0,e.hp/e.maxHp),3);if(e.boss){ctx.fillStyle='#f2eee8';ctx.font='bold 10px Manrope';ctx.textAlign='center';ctx.fillText(bossName(e.type).toUpperCase(),e.x,e.y-e.radius-14)}}
function drawDungeon(w,h){ctx.fillStyle='#17191a';ctx.fillRect(0,0,w,h);const tw=76,th=55;for(let row=0,y=-th;y<h;y+=th,row++){let offset=row%2?tw/2:0;for(let col=-1,x=-tw+offset;x<w;x+=tw,col++){let n=Math.abs((col*37+row*61+col*row*13)%13),base=25+n;ctx.fillStyle=`rgb(${base},${base+2},${base+3})`;ctx.fillRect(x+1,y+1,tw-2,th-2);ctx.strokeStyle='#a8a28f12';ctx.lineWidth=1;ctx.strokeRect(x+3,y+3,tw-6,th-6);ctx.strokeStyle='#090b0c77';ctx.beginPath();ctx.moveTo(x+5,y+th-3);ctx.lineTo(x+tw-4,y+th-3);ctx.moveTo(x+tw-3,y+5);ctx.lineTo(x+tw-3,y+th-3);ctx.stroke();if(n===2||n===8){ctx.strokeStyle='#b9b2a01a';ctx.beginPath();ctx.moveTo(x+18,y+12);ctx.lineTo(x+22,y+17);ctx.lineTo(x+19,y+22);ctx.stroke()}}}const wall=(x,y,w,h)=>{ctx.fillStyle='#282725';ctx.fillRect(x,y,w,h);ctx.strokeStyle='#090a0b';ctx.lineWidth=2;for(let yy=y;yy<y+h;yy+=20){let off=(Math.floor((yy-y)/20)%2)*28;for(let xx=x-off;xx<x+w;xx+=56){ctx.strokeRect(xx+2,yy+2,52,16)}}};wall(0,0,960,25);wall(0,575,960,25);wall(0,0,24,600);wall(936,0,24,600);ctx.strokeStyle='#d1b77b19';ctx.setLineDash([3,9]);ctx.beginPath();ctx.arc(480,300,235,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);[[205,150,.9],[752,170,1],[172,432,.9],[765,426,.85],[470,90,.7]].forEach((v,i)=>drawSkeleton(v[0],v[1],v[2],i*.7));[[390,145,'helm'],[610,410,'shield'],[340,450,'sword'],[700,290,'helm'],[250,300,'shield']].forEach((v,i)=>drawBrokenArmor(v[0],v[1],v[2],i*.83));[[76,82],[884,83],[75,515],[885,515]].forEach((v,i)=>drawTorch(v[0],v[1],i))}
function drawSkeleton(x,y,s,angle){ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.scale(s,s);ctx.strokeStyle='#c8bfa1';ctx.lineWidth=2.2;ctx.lineCap='round';ctx.fillStyle='#bcb298';ctx.beginPath();ctx.ellipse(-13,-2,6,5,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#342f29';ctx.beginPath();ctx.arc(-15,-3,1.4,0,6.28);ctx.arc(-11,-3,1.4,0,6.28);ctx.fill();ctx.strokeStyle='#bcb298';ctx.beginPath();ctx.moveTo(-7,-1);ctx.lineTo(10,2);ctx.moveTo(-1,0);ctx.lineTo(-2,9);ctx.moveTo(3,1);ctx.lineTo(2,10);ctx.moveTo(7,2);ctx.lineTo(6,10);ctx.moveTo(11,2);ctx.lineTo(10,9);ctx.moveTo(1,9);ctx.lineTo(13,11);ctx.moveTo(2,10);ctx.lineTo(-7,17);ctx.moveTo(13,11);ctx.lineTo(19,17);ctx.moveTo(-4,5);ctx.lineTo(-10,12);ctx.moveTo(11,4);ctx.lineTo(17,-2);ctx.stroke();ctx.restore()}
function drawBrokenArmor(x,y,type,a){ctx.save();ctx.translate(x,y);ctx.rotate(a);ctx.lineWidth=2;if(type==='helm'){ctx.fillStyle='#55534a';ctx.strokeStyle='#978d75';ctx.beginPath();ctx.arc(0,0,9,Math.PI,Math.PI*2);ctx.lineTo(9,6);ctx.lineTo(-9,6);ctx.closePath();ctx.fill();ctx.stroke();ctx.strokeStyle='#242526';ctx.beginPath();ctx.moveTo(-4,2);ctx.lineTo(1,6);ctx.lineTo(4,1);ctx.stroke()}else if(type==='shield'){ctx.fillStyle='#574a3d';ctx.strokeStyle='#9c845b';ctx.beginPath();ctx.moveTo(0,-11);ctx.lineTo(10,-7);ctx.lineTo(8,6);ctx.lineTo(0,12);ctx.lineTo(-9,5);ctx.lineTo(-10,-7);ctx.closePath();ctx.fill();ctx.stroke();ctx.strokeStyle='#b09666';ctx.beginPath();ctx.moveTo(-7,-3);ctx.lineTo(2,0);ctx.lineTo(-2,7);ctx.stroke()}else{ctx.strokeStyle='#77786f';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-9,9);ctx.lineTo(9,-9);ctx.stroke();ctx.strokeStyle='#ae9d76';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(5,-13);ctx.lineTo(13,-5);ctx.moveTo(-1,5);ctx.lineTo(3,9);ctx.stroke()}ctx.restore()}
function drawTorch(x,y,seed){let flicker=Math.sin(game.timer*12+seed*2.7)*2;const glow=ctx.createRadialGradient(x,y-10,2,x,y-10,82);glow.addColorStop(0,'#f5a3472a');glow.addColorStop(1,'#f5a34700');ctx.fillStyle=glow;ctx.fillRect(x-82,y-92,164,164);ctx.fillStyle='#524437';ctx.fillRect(x-5,y-4,10,15);ctx.fillStyle='#87704e';ctx.fillRect(x-8,y-6,16,4);ctx.fillStyle='#3d3025';ctx.fillRect(x-2,y-17,4,12);ctx.fillStyle='#f27638';ctx.beginPath();ctx.moveTo(x,y-27-flicker);ctx.quadraticCurveTo(x+9,y-17,x,y-10);ctx.quadraticCurveTo(x-8,y-16,x,y-27-flicker);ctx.fill();ctx.fillStyle='#ffd277';ctx.beginPath();ctx.moveTo(x,y-22-flicker);ctx.quadraticCurveTo(x+4,y-16,x,y-12);ctx.quadraticCurveTo(x-4,y-17,x,y-22-flicker);ctx.fill()}
function draw(){if(!ctx||!game)return;let w=960,h=600;ctx.clearRect(0,0,w,h);drawDungeon(w,h);
game.pickups.forEach(w=>{let color=classes.find(c=>c.id===w.classId)?.color||'#e6a955',pulse=Math.sin(game.timer*5+w.phase)*2;ctx.save();ctx.globalAlpha=.82;ctx.shadowColor=color;ctx.shadowBlur=15;ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();ctx.arc(w.x,w.y+pulse,13,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#17191a';ctx.beginPath();ctx.arc(w.x,w.y+pulse,9,0,Math.PI*2);ctx.fill();ctx.fillStyle=color;ctx.font='14px Manrope';ctx.textAlign='center';ctx.fillText(w.item.icon,w.x,w.y+5+pulse);ctx.shadowBlur=0;ctx.font='7px DM Mono';ctx.fillText(w.item.name,w.x,w.y+24+pulse);ctx.restore()});game.hearts.forEach(h=>{ctx.save();let pulse=1+Math.sin(h.phase)*.09;ctx.translate(h.x,h.y+Math.sin(h.phase*1.3)*2);ctx.scale(pulse,pulse);ctx.shadowColor='#fa5869';ctx.shadowBlur=14;ctx.fillStyle='#f36a78';ctx.beginPath();ctx.moveTo(0,8);ctx.bezierCurveTo(-4,4,-10,0,-9,-5);ctx.bezierCurveTo(-8,-11,-1,-11,0,-5);ctx.bezierCurveTo(2,-11,9,-11,9,-5);ctx.bezierCurveTo(10,0,4,5,0,8);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#ffd7d2';ctx.beginPath();ctx.arc(-4,-5,1.4,0,Math.PI*2);ctx.fill();ctx.restore()});game.orbs.forEach(o=>{ctx.save();ctx.translate(o.x,o.y+Math.sin(o.phase)*2);ctx.shadowBlur=16;ctx.shadowColor='#73cce0';ctx.fillStyle='#83d5e3';ctx.beginPath();ctx.arc(0,0,o.r,0,Math.PI*2);ctx.fill();ctx.restore()});game.effects.forEach(e=>{ctx.save();ctx.globalAlpha=Math.max(0,e.life*2.7);ctx.strokeStyle=e.color;ctx.lineWidth=2;ctx.beginPath();ctx.arc(e.x,e.y,e.r*(1.2-e.life),0,Math.PI*2);ctx.stroke();ctx.restore();e.life-=.018});game.effects=game.effects.filter(e=>e.life>0);
game.shots.forEach(s=>{ctx.save();ctx.translate(s.x,s.y);if(s.kind==='mote'||s.kind==='ember'){ctx.shadowColor=s.kind==='ember'?'#f05c48':'#83d5e3';ctx.shadowBlur=12;ctx.fillStyle=s.kind==='ember'?'#ff7257':'#a6eee6';ctx.beginPath();ctx.arc(0,0,s.kind==='ember'?6:5,0,Math.PI*2);ctx.fill()}else if(s.lightning||s.kind==='lightningArrow'){ctx.rotate(Math.atan2(s.vy,s.vx));ctx.strokeStyle='#8ceeff';ctx.shadowColor='#48caff';ctx.shadowBlur=13;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-12,0);ctx.lineTo(-6,-4);ctx.lineTo(-2,3);ctx.lineTo(3,-4);ctx.lineTo(8,1);ctx.lineTo(14,-1);ctx.stroke()}else{ctx.rotate(Math.atan2(s.vy,s.vx));ctx.fillStyle=s.kind==='critArrow'?'#ffe18b':'#d3e2af';if(s.kind==='critArrow'){ctx.shadowColor='#ffd36a';ctx.shadowBlur=10}ctx.fillRect(-7,-2,14,4)}ctx.restore()});game.enemies.forEach(e=>{ctx.save();ctx.translate(e.x,e.y);ctx.fillStyle=e.boss?'#b84544':'#80655b';ctx.strokeStyle=e.boss?'#ed7560':'#d7a174';ctx.lineWidth=e.boss?3:1.5;ctx.beginPath();ctx.arc(0,0,e.radius,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#17151a';ctx.beginPath();ctx.arc(-e.radius*.28,-2,2,0,6.28);ctx.arc(e.radius*.28,-2,2,0,6.28);ctx.fill();ctx.fillStyle='#ffffff25';ctx.fillRect(-e.radius,-e.radius-9,e.radius*2,3);ctx.fillStyle=e.boss?'#ed7560':'#d7a174';ctx.fillRect(-e.radius,-e.radius-9,e.radius*2*Math.max(0,e.hp/e.maxHp),3);ctx.restore();drawEnemySprite(e)});game.players.forEach(p=>{ctx.save();ctx.translate(p.x,p.y);if(p.shield>0){p.shield-=.016;ctx.strokeStyle=p.color;ctx.globalAlpha=.5;ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,19,0,6.28);ctx.stroke()}ctx.globalAlpha=p.alive?1:.3;ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(0,0,12,0,6.28);ctx.fill();ctx.fillStyle='#16151a';ctx.beginPath();ctx.arc(0,-1,5,0,6.28);ctx.fill();ctx.fillStyle='#f4ece1';ctx.font='10px Manrope';ctx.textAlign='center';ctx.restore();drawPlayer(p)})}
window.addEventListener('keydown',e=>{let k=e.key.toLowerCase();if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();keys[k]=true});window.addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'){canvas.setPointerCapture(e.pointerId);touch={startX:e.offsetX,startY:e.offsetY,x:0,y:0,id:e.pointerId}}});canvas.addEventListener('pointermove',e=>{if(touch&&touch.id===e.pointerId){let r=canvas.getBoundingClientRect(),dx=(e.clientX-r.left-touch.startX)/70,dy=(e.clientY-r.top-touch.startY)/70,m=Math.max(1,Math.hypot(dx,dy));touch.x=Math.max(-1,Math.min(1,dx/m*Math.min(1,m)));touch.y=Math.max(-1,Math.min(1,dy/m*Math.min(1,m)))}});canvas.addEventListener('pointerup',()=>touch=null);canvas.addEventListener('pointercancel',()=>touch=null);
setInterval(()=>{if(mode==='join'&&hostConn?.open&&game){let p=game.players.find(x=>x.id===clientId);let i={type:'input',x:(keys.d?1:0)-(keys.a?1:0),y:(keys.s?1:0)-(keys.w?1:0),ability:!!keys[' ']};if(touch){i.x=touch.x;i.y=touch.y}hostConn.send(i)}else if(mode==='host'&&game&&!game.upgradePending)syncParty()},100);
})();




























